#!/usr/bin/env bash
#
# DESCRIPTION:
#
#   Set the bash prompt according to:
#    * the active virtualenv
#    * the branch/status of the current git repository
#    * the return value of the previous command
#
# USAGE:
#
#   1. Save this file as ~/.bash_prompt
#   2. Add the following line to the end of your ~/.bashrc or ~/.bash_profile:
#        . ~/.bash_prompt
#
# LINEAGE:
#
#   Based on works by woods & insin:
#   https://gist.github.com/31967
#   https://gist.github.com/insin/1425703
#
# Colors are needed by several bash-scripts and this is just one of them
# So, let's place colors in a special file
# ~/.config/aliasrc_bash_colors

# Main interface function first. Set the full bash prompt.
function set_bash_prompt () {
  # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
  # return value of the last command.
  set_prompt_symbol $?

  # Set the PYTHON_VIRTUALENV variable.
  set_virtualenv

  # Set the BRANCH variable.
  is_git_repository && set_git_branch || BRANCH=''
    
  # Set the bash prompt variable. There must be 2 lines(!)
  PS1="${PYTHON_VIRTUALENV}${Orange}\[\$(date +%H:%M)\] ${BBlue}\$PWD${Color_Off} ${BRANCH}
${PROMPT_SYMBOL} "
}

# And now details. Check, how this magic is done:
# Detect whether the current directory is a git repository.
function is_git_repository {
  git branch > /dev/null 2>&1
}

# Determine the branch/state information for the git repository.
function set_git_branch {
  # Capture the output of the "git status" command.
  git_status="$(git status 2> /dev/null)"

  # Set color based on clean/staged/dirty.
  case "${git_status}" in
      *"working tree clean"*)
        state="${Green}";;
      *"Changes to be committed"*)
        state="${Yellow}";;
      *)
        state="${Red}";;
  esac

  # Set arrow icon based on status against remote.
  case "${git_status}" in
      *${remote_pattern_ahead}*)
        remote="↑";;
      *${remote_pattern_behind}*)
        remote="↓";;
      *)
        remote="";;
  esac

  # Get the name of the branch.
  branch="$(git rev-parse --abbrev-ref HEAD)"

  # Set the final branch string.
  BRANCH="${state}(${branch})${remote}${Color_Off} "
}

# Prompt symbol color/shape based on the return value of the previous command.
function set_prompt_symbol () {
  PROMPT_SYMBOL="${Purple}\$${Color_Off}"
  [[ $1 -eq 0 ]] && PROMPT_SYMBOL="${BAqua}>${Color_Off}"
}

# Determine active Python virtualenv details.
function set_virtualenv () {
  PYTHON_VIRTUALENV="${Green}(`basename \"$VIRTUAL_ENV\"`)${Color_Off} "
  [[ -z "$VIRTUAL_ENV" ]] && PYTHON_VIRTUALENV=""
}

# Tell bash to execute this function just before displaying its prompt.
PROMPT_COMMAND=set_bash_prompt
